[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 3

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256

# Gas reporting
gas_reports = ["*"]

# Formatter
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

# Network configurations
[rpc_endpoints]
# BSC (BNB Chain)
bsc = "${BSC_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"

# Ethereum
mainnet = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# Base
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

# Local development
localhost = "http://localhost:8545"

# Block explorer API keys for verification
[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
